version: '3.3'
services:
  drupal:
    image: drupal
    restart: always
    ports:
      - "8181:80"
    volumes:
      - drupal_data:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

volumes:
 db_data: {}
 drupal_data: {}
