version: '3.1'
services:
  redmine:
    image: redmine
    restart: always
    ports:
      - "8080:80"
    environment:
      REDMINE_DB_MYSQL: redmine
      REDMINE_DB_PASSWORD: redmine

  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: somewordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
