version: '3.8'
services:
  web:
    image: "dgruploads/python_count_app"
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
