version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
